resources:
  pipelines:
  - pipeline: Deploy to ASP
    source: Deploy to ASP
    trigger:
      branches:
        include:
        - refs/heads/master
trigger:
  - none
  
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: Npm@1
    displayName: Run Cypress Test
    continueOnError: True
    inputs:
      command: custom
      verbose: false
      customCommand: run test
  - task: Npm@1
    displayName: Run npm build
    continueOnError: True
    inputs:
      command: custom
      verbose: false
      customCommand: run build
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: build
...
